-- ============================================================
-- Migration 001: Core schema
-- Survivor Pool app — all 7 tables with constraints & FKs
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ============================================================
-- ENUMS
-- ============================================================

create type user_role as enum ('commissioner', 'player');
create type user_status as enum ('active', 'eliminated', 'pending_approval');
create type pick_outcome as enum ('safe', 'eliminated', 'no_pick');
create type join_request_status as enum ('pending', 'approved', 'rejected');

-- ============================================================
-- TABLE: users
-- Pool participants (linked to Supabase Auth via id)
-- ============================================================

create table users (
  id             uuid primary key references auth.users(id) on delete cascade,
  name           text not null,
  email          text not null unique,
  role           user_role not null default 'player',
  status         user_status not null default 'pending_approval',
  eliminated_week int null,
  created_at     timestamptz not null default now()
);

-- ============================================================
-- TABLE: tribes
-- Master list of all tribes (starting + merged)
-- ============================================================

create table tribes (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  color      text not null,         -- hex color code e.g. "#F97316"
  is_merged  boolean not null default false,
  created_at timestamptz not null default now()
);

-- ============================================================
-- TABLE: contestants
-- Full 24-person cast; tribe info lives in contestant_tribe_history
-- ============================================================

create table contestants (
  id               uuid primary key default gen_random_uuid(),
  name             text not null,
  is_eliminated    boolean not null default false,
  eliminated_week  int null,
  created_at       timestamptz not null default now()
);

-- ============================================================
-- TABLE: contestant_tribe_history
-- Week-by-week tribe assignments per contestant
-- ============================================================

create table contestant_tribe_history (
  id            uuid primary key default gen_random_uuid(),
  contestant_id uuid not null references contestants(id) on delete cascade,
  tribe_id      uuid not null references tribes(id) on delete restrict,
  week_number   int not null,
  created_at    timestamptz not null default now(),
  unique (contestant_id, week_number)
);

create index idx_cth_contestant_week on contestant_tribe_history (contestant_id, week_number desc);

-- ============================================================
-- TABLE: weeks
-- One row per episode
-- ============================================================

create table weeks (
  id                        uuid primary key default gen_random_uuid(),
  week_number               int not null unique,
  episode_date              timestamptz not null,   -- air date; also the pick deadline
  is_locked                 boolean not null default false,
  is_results_entered        boolean not null default false,
  eliminated_contestant_id  uuid null references contestants(id) on delete set null,
  created_at                timestamptz not null default now()
);

-- ============================================================
-- TABLE: picks
-- One pick per user per week
-- ============================================================

create table picks (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null references users(id) on delete cascade,
  week_id                  uuid not null references weeks(id) on delete cascade,
  contestant_id            uuid null references contestants(id) on delete set null,
  outcome                  pick_outcome null,
  is_commissioner_override boolean not null default false,
  created_at               timestamptz not null default now(),
  unique (user_id, week_id)
);

create index idx_picks_user on picks (user_id);
create index idx_picks_week on picks (week_id);

-- ============================================================
-- TABLE: invite_links
-- One-use or multi-use invite tokens generated by commissioner
-- ============================================================

create table invite_links (
  id         uuid primary key default gen_random_uuid(),
  token      text not null unique,
  created_by uuid not null references users(id) on delete cascade,
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- ============================================================
-- TABLE: join_requests
-- Users who clicked an invite link and are awaiting approval
-- ============================================================

create table join_requests (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  email        text not null,
  invite_token text not null,
  status       join_request_status not null default 'pending',
  created_at   timestamptz not null default now()
);
